### PR TITLE
reformat GerbView section 2 and 3.

### PR DESCRIPTION
**Pull request by kinichiro**
it is hard to read section 2 and 3 of GerbView
because of its less formatting.
Would you like formatting like this PR ?
I think this is better, but we need to translate .po of GerbView again.
Changes are a lot.

### CODE REVIEW

**Comment by nickoe** [comment]
Hmm, I wonder why the section "2. Gerber Format Info" is in the gerbview documentation. It looks like it has been taken directly from: http://www.artwork.com/gerber/appl2.htm

I don't immediately see the purpose of reprinting that in the gerbview manual, we could link it if necessary or relevant.

**Comment by kinichiro** [comment]
Oh, I also noticed the section 3 is from: http://www.artwork.com/gerber/274x/rs274x.htm

**Comment by nickoe** [comment]
Indeed. I wonder if we are even allowed to reprint theese pages. But they were also existing in the original odf/pdf sources for gerbview.

http://bazaar.launchpad.net/~kicad-developers/kicad/doc/view/head:/doc/help/en/eeschema.pdf

**Comment by kinichiro** [comment]
I also wondered why the explanations about D-code and RS274X are included in the KiCad GerbView manual when I translated this to Japanese ;-)

And I noticed that the section 2 is incomplete copy from artwork pdf, because end of it seems to be cut off, shorten.

Will you keep these 2 sections still or cut off and just leave links about these 2 PDFs at the end of the GerbView manual ?

**Comment by nickoe** [comment]
I asked the original author about this and he replied with:
> I am thinking chapters 2 and 3 are now outdated and should be just removed.
> 
> Here is the link to the latest Gerber file format specification:
> http://www.ucamco.com/files/downloads/file/81/the_gerber_file_format_specification.pdf
> 
> which could replace chapters 2 and 3.
> 
> Thanks to take care of that.
> 
> --
> Jean-Pierre CHARRAS

So I think that concludes that we shall remove the two sections and just link to the gerber specification.  I am sorry for you using time to translate something which will be removed. Please don't hesitate to ask a question about the docs if you find something strange like this. Rember the docs was old when we becan to convert them to asciidoc.

Should I pull out the sections before I merge the pull request #111 or after?

(I will wait removing the sections to make you have a chance to reply).

**Comment by nickoe** [comment]
Other maintainers and translaters please be aware of the above.
@ciampix @keruseykaryu @yoneken

**Comment by kinichiro** [comment]
@nickoe 
I see.
I'm glad to find this issue before KiCad docs are released.

>Should I pull out the sections before I merge the pull request #111 or after?
Sure, go ahead, please.

Thanks for your hard work.

**Comment by kinichiro** [comment]
If you modify GerbView_chapter_01.adoc,
could you fix about "Load Dcodes" menu, too ?

1.6.1 "File -> Load Dcodes" is obsolete,
and I think these lines should be removed from GerbView_chapter_01.adoc.
<pre>
    219 There are 2 special commands:
    220
    221 * Load Dcodes.
    222 * Export to Pcbnew.
    223
    224 Load Dcodes is now obsolete. It is used to load a Dcode file definition
    225 when using old RS 274 D Gerber files.
    226
    227 Unfortunately, Dcode file definition has no standard format.
</pre>
And images/0B00000014A8CB8D3BC.png should be replaced by new one.

**Comment by keruseykaryu** [comment]
@nickoe: 
> Other maintainers and translators please be aware of the above.

I'm sorry Nick, but this will deal with my successor - if he will.

**Comment by nickoe** [comment]
Please have a look at https://github.com/ciampix/kicad-doc/pull/113  and verify that I did not do anything stupid.

**Comment by nickoe** [comment]
I have now removed theese two sections and this pull request is there for not valid anymore.

@kinichiro  I fixed what you asked about the load dcodes.

**Pull request closed without merging**
