### PR TITLE
Compile epub with cmake

### PR DESCRIPTION
**Pull request by Caerbannog**
Compilation of epub with CMake the same as for PDF. I reused the docinfo cover page from the legacy Makefile.
Hopefully there is not much more to do before removing the legacy Makefile and related make.sh

### CODE REVIEW

**Comment by kinichiro** [comment]
Japanese epub outputs seems not good.
All the Japanese characters are garbled.
html and pdf are OK.

**Comment by nickoe** [comment]
Thank you, it seems to work ok, so I will merge it. Keep the fixes comming.

**Comment by nickoe** [comment]
@kinichiro In what way? I opened the one in the artifacts for the builds, and it seems ok to me. Not that I can read japanese.

http://ci.kicad-pcb.org/job/kicad-doc-testing-pull-request/118/artifact/build-cmake/src/Pcbnew/ja/Pcbnew.epub

**Comment by kinichiro** [comment]
It looks like this on my PC.
pcbnew_ja_epub_pdf

**Comment by kinichiro** [comment]
when generating epub with `./make.sh Pcbnew-ja.epub` under src/Pcbnew/ directory,
I could get fine epub file, like this.
pcbnew_ja_epub_ok
Then, I think cmake Japanese epub build has some issue.

**Comment by nickoe** [comment]
Ok, so we have some more font issues here.

**Comment by nickoe** [comment]
I guess this can help us: http://www.methods.co.nz/asciidoc/faq.html#X5

**Pull request merged**
