### PR TITLE
Update KiCad.adoc

### PR DESCRIPTION
**Pull request by djsbriscoe**
Minor English Grammar and spelling corrections.

### CODE REVIEW

**Comment by djsbriscoe** [comment]
First Kicad document review and editing effort. Please be kind and point out any errors or omissions. Thanks.

**Comment by nickoe** [comment]
Hi djsbriscore, why did you close this pull request?

Please read: https://help.github.com/articles/closing-a-pull-request/

**Comment by djsbriscoe** [comment]
Closed pull request by mistake. Didn't know what I was doing , sorry.

**Comment by nickoe** [comment]
Thank you for your contribution. It looks good, so I will merge this.

**Pull request merged**
