### PR TITLE
Clean up Main Top Menu

### PR DESCRIPTION
**Pull request by cpavlina**
Okay, here's some more tidying up, this time in the Eeschema menu bar documentation. This one was quite out of date; I replaced all the screenshots, updated names, etc.

### CODE REVIEW

**Comment by cpavlina** [comment]
Any idea why the auto Jenkins build failed?

**Comment by nickoe** [comment]
Mayne because of this:13:24:09 a2x: ERROR: missing resource: /home/kicad/workspace/kicad-doc-testing-pull-request/src/Eeschema/images/100000000000021400000283EC98FC85.png
13:24:09 ../Makefile:176: recipe for target 'Eeschema.epub' failed

**Comment by cpavlina** [comment]
Interesting.... a cmake build doesn't give that message. Had to use make.sh.

Okay, I think it's fixed.

**Comment by ciampix** [comment]
Ok! Thanks!

**Pull request merged**
