### PR TITLE
Update Getting_Started manual. Create initial stuff for IDF_Exporter manual.

### PR DESCRIPTION
**Pull request by keruseykaryu**

### CODE REVIEW

**Comment by ciampix** [comment]
Thanks!

**Comment by danger89** [comment]
Wait a sec. The Getting started is only in Polish & Italian?  I'm dutch speaker from Holland. I can create a dutch Getting started as well!

**Comment by nickoe** [comment]
Go go!
Den 20/05/2015 11.13 skrev "Melroy van den Berg" <notifications@github.com>:

**Comment by ciampix** [comment]
On Wed, May 20, 2015 at 02:13:02AM -0700, Melroy van den Berg wrote:
> Wait a sec. The Getting started is only in Polish & Italian?  I'm dutch
> speaker from Holland. I can create a dutch Getting started as well!

If you are not experienced I can create a .po template file to semplify
your first translation. Tell me if you want I do it for you.

--


Marco Ciampa

I know a joke about UDP, but you might not get it.

+------------------------+
| GNU/Linux User  #78271 |
| FSFE fellow       #364 |
+------------------------+

**Comment by danger89** [comment]
@ciampix Thx. I want a nl.po (The Netherlands, Language: Dutch), so I can change the whole content of: https://raw.githubusercontent.com/ciampix/kicad-doc/master/src/Getting_Started_in_KiCad/Getting_Started_in_KiCad.adoc.

**Comment by ciampix** [comment]
On Thu, May 21, 2015 at 01:24:40AM -0700, Melroy van den Berg wrote:

> @ciampix Thx. I want a nl.po (The Netherlands, Language: Dutch), so I
> can change the whole content of:
> https://raw.githubusercontent.com/ciampix/kicad-doc/master/src/Getting_Started_in_KiCad/Getting_Started_in_KiCad.adoc.

Done. Now you have a nice po/nl.po file editable with your po editor of
choice (poedit, ktranslator, emacs, vi, etc.) under 
https://raw.githubusercontent.com/ciampix/kicad-doc/master/src/Getting_Started_in_KiCad/

Happy translation!

Regards,

--


Marco Ciampa

I know a joke about UDP, but you might not get it.

+------------------------+
| GNU/Linux User  #78271 |
| FSFE fellow       #364 |
+------------------------+

**Comment by danger89** [comment]
THX!

**Pull request merged**
